apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql-ephemeral
  name: mysql-ephemeral
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
      - name: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "1"
      ports:
      - name: mysql
        containerPort: 3306
